# Основные настройки бота
telegram_channel: '@test_chanellmy'
bot_token: 'YOUR_BOT_TOKEN'  # Токен бота от @BotFather

# ID администраторов бота
admin_user_ids:
  - 791291895
  - 454036002
  - 453698873

# Настройки базы данных PostgreSQL
postgres:
  dbname: "telegram_bot_db"
  user: "bot_user"
  password: "your_password_here"
  host: "localhost"
  port: 5432

# Интервалы парсинга (в секундах)
intervals:
  default: 3600  # 1 час
  telegram: 1800  # 30 минут
  rss: 3600      # 1 час
  html: 7200     # 2 часа

# Источники данных
sources:
  # RSS-ленты
  - name: "Хабр"
    type: "rss"
    url: "https://habr.com/ru/rss/hubs/{tag}/articles/"
    tags:
      - "python"
      - "machine_learning"
      - "artificial_intelligence"
      - "bigdata"
      - "data_engineering"

  # HTML-сайты
  - name: "QuData"
    type: "html"
    url: "https://qudata.com/ru/news-ai/tags/neural-network/"
    selectors:
      article: "article.post-box"
      title: "h3.entry-title a"
      link: "h3.entry-title a"
      date: "span.posted-on"
      description: "div.entry-summary p"
      image: "div.entry-media img"
    default_tags:
      - "neural-network"
      - "AI"
      - "машинное обучение"

  # Telegram каналы (веб-парсинг)
  - name: "Open Data Science"
    type: "telegram_web"
    username: "opendatascience"  # Без @
    tags:
      - "data_science"
      - "machine_learning"
      - "AI"

  - name: "Нейронные сети"
    type: "telegram_web"
    username: "pytorchs"  # Без @
    tags:
      - "neural_networks"
      - "deep_learning"
      - "pytorch"


      
  - name: Test2_Glebus
    type: telegram_web
    username: "@test2_glebus"
  - name: ICT_Moscow_AI
    type: telegram_web
    username: "@ict_moscow_ai"
  - name: "AI Machine Learning Big Data"
    type: "telegram_web"
    username: "@ai_machinelearning_big_data"
  - name: "Data Secrets"
    type: "telegram_web"
    username: "@data_secrets"
  - name: "Renat Alimbekov"
    type: "telegram_web"
    username: "@renat_alimbekov"
  - name: "DSPROGLIB"
    type: "telegram_web"
    username: "@dsproglib"
  - name: "Small Data Science"
    type: "telegram_web"
    username: "@smalldatascience"
  - name: "DEVS Pro"
    type: "telegram_web"
    username: "@devsp"
  - name: "NoML Digest"
    type: "telegram_web"
    username: "@noml_digest"
  - name: "AddMeTo"
    type: "telegram_web"
    username: "@addmeto"
  - name: "CryptoValerii"
    type: "telegram_web"
    username: "@cryptovalerii"
  - name: "Gonzo ML"
    type: "telegram_web"
    username: "@gonzo_ML"
  - name: "DL & NLP"
    type: "telegram_web"
    username: "@dlinnlp"
  - name: "SV9T Channel"
    type: "telegram_web"
    username: "@sv9t_channel"
  - name: "Open Data Science"
    type: "telegram_web"
    username: "@opendatascience"
